SRCP = hdnum-tutorial-beamer
SRCA = hdnum-tutorial-article

beamer:
	latexmk $(SRCP)

art:
	latexmk $(SRCA)

clean:
	rm *.bbl *.blg *.dvi *.aux *.idx *.log *.lof *.toc *.lot *.ind *.ilg *.snm *.nav *.out *.vrb *.fls *_latexmk
